# Generated by Django 5.2.7 on 2025-11-10 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
